services:

  server:
    restart: always
    container_name: nginx_dj
    image: nginx:alpine
    working_dir: /application
    ports:
      - "127.0.0.1:3536:80"
    volumes:
      - ./:/var/www/dj
      - ./deploy/nginx/conf.d:/etc/nginx/conf.d
      - /home/reports/projects/reports_storage:/var/www/dj/storage
    networks:
      - dj

  app:
    restart: always
    container_name: app_dj
    build:
      context: ./deploy/dockerfiles
      dockerfile: local-alpine.Dockerfile
      args:
        WWWUSER: '${WWWUSER:-1000}'
        WWWGROUP: '${WWWGROUP:-1000}'
    working_dir: /var/www/dj
    volumes:
      - ./:/var/www/dj
      - ./deploy/php/uploads.ini:/usr/local/etc/php/php.ini
      - /home/reports/projects/reports_storage:/var/www/dj/storage
    networks:
      - dj

  pgsql:
    restart: always
    container_name: psql_dj
    image: postgres:14.5-alpine
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - dj-pgsql-data:/var/lib/postgresql/data
    ports:
      - '5451:5432'
    networks:
      - dj

  mysql:
    restart: always
    container_name: mysql_dj
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-secret}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - dj-mysql-data:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - dj

  cache:
    restart: always
    container_name: redis_dj
    image: redis:7.2.3
    volumes:
      - dj-cache-data:/data
    ports:
      - "127.0.0.1:6353:6379"
    networks:
      - dj

volumes:
  dj-pgsql-data:
    driver: local
  dj-cache-data:
    driver: local
  dj-mysql-data:
    driver: local

networks:
  dj:
    driver: bridge
